### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by juhaszp95** [quartiq/stabilizer-stream#11]
Hello,

This looks like a very useful project, but I didn't find any documentation on how to use it. Specifically, it'd be very useful for me to know what the required steps are to recreate the interface shown in the video in the readme.

If you could share / point me to that, that would be much appreciated!

**Comment by ryan-summers** [comment]
Generally you use this repository like you would any other rust project:
```
cargo run --bin psd
```

That being said, it looks like there may be some minor issues in the source that need to be fixed as well. 

CC @jordens - looks like we have some various arg setup issues:
```
$ cargo run --bin psd
   Compiling stabilizer-stream v0.1.1 (C:\Users\rsummers\Documents\repositories\quartiq\stabilizer-streaming)
    Finished dev [unoptimized + debuginfo] target(s) in 6.38s
     Running `target\debug\psd.exe`
thread 'main' panicked at C:\Users\rsummers\.cargo\registry\src\index.crates.io-6f17d22bba15001f\clap_builder-4.5.2\src\builder\debug_asserts.rs:112:17:
Command stabilizer-stream: Short option names must be unique for each argument, but '-i' is in use by both 'ip' and 'integrate'
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\debug\psd.exe` (exit code: 101)

```

**Comment by ryan-summers** [comment]
You can work around the build issues by using release:
```
cargo run --release --bin psd -- <ARGS>
```

So to get an initial help interface:
```
cargo run --release --bin psd -- -h
```

There indeed should be some more documentation about usage in the README though

**Comment by juhaszp95** [comment]
Thanks for the quick feedback. The debug build indeed gives me the same error as well, hence raising the issue.

I've tried running `cargo run --release --bin psd -- -h`  but this doesn't return anything for me unfortunately.

**Comment by ryan-summers** [comment]
Hmm that seems odd. You should see help output in the console:
```
    Finished release [optimized + debuginfo] target(s) in 2m 50s
     Running `target\release\psd.exe -h`
Stabilizer stream source options

Usage: psd.exe [OPTIONS]

Options:
  -i, --ip <IP>
          The local IP to receive streaming data on [default: 0.0.0.0]
  -p, --port <PORT>
          The UDP port to receive streaming data on [default: 9293]
  -f, --file <FILE>
          Use frames from the given file
  -f, --frame-size <FRAME_SIZE>
          Frame size in file (8 + n_batches*n_channel*batch_size) [default: 1448]
  -r, --repeat
          On a file, wrap around and repeat
  -r, --raw <RAW>
          Single f32 raw trace, architecture dependent endianess
  -n, --noise <NOISE>
          Power law noise with psd f^noise
  -d, --dsm <DSM>
          Delta sigma modulator (MASH-1-1-1) with given frequency calibration marker
  -d, --detrend <DETREND>
          Segment detrending method [default: mean] [possible values: none, midpoint, span, mean, linear]
  -f, --fs <FS>
          Sample rate in Hertz [default: 1]
  -a, --avg-max <AVG_MAX>
          Averaging limit [default: 1000]
  -a, --avg-min <AVG_MIN>
          Exclude PSD stages with less than or equal this averaging level [default: 1]
  -a, --avg <AVG>
          Extrapolated averaging count at the top stage [default: 4294967295]
  -k, --keep-overlap
          Don't remove low resolution bins
  -k, --keep-transition-band
          Don't remove bins in the filter transition band
  -i, --integrate
          Integrate jitter (linear)
  -i, --integral-start <INTEGRAL_START>
          [default: 0.000001]
  -i, --integral-end <INTEGRAL_END>
          [default: 0.5]
  -h, --help
          Print help (see more with '--help')
```

**Comment by juhaszp95** [comment]
That's very strange. I'm using PowerShell on Windows 11, but I checked I get the same output on regular Windows CMD.

I only get the following output, nothing else:
```
    Finished release [optimized + debuginfo] target(s) in 0.87s
     Running `target\release\psd.exe -h`
```

**Comment by juhaszp95** [comment]
I've just tried running this on a Linux PC, where I could get the help menu to display. However, I then bumped into another issue. When I run `cargo run --release --bin psd -- -i 10.255.6.129` (to get some stream to my IP), I get the following error:
```
    Finished release [optimized + debuginfo] target(s) in 0.12s
     Running `target/release/psd -i 10.255.6.129`
thread 'main' panicked at /home/juhasz/.cargo/registry/src/index.crates.io-6f17d22bba15001f/xkbcommon-dl-0.4.2/src/x11.rs:59:28:
Library libxkbcommon-x11.so could not be loaded.
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by jordens** [comment]
Presumably `libxkbcommon-x11` is not installed.

**Comment by jordens** [comment]
short arg collisions fixed in 240ad75d1fd19fc25ebb46990e9b5b33636a1c59

**Comment by juhaszp95** [comment]
Thanks - I've now managed to get the UI to come up once I installed `libxkbcommon-x11-0` on a Linux machine - it still doesn't run on Windows.

However, the UI shows no FFT data coming in, the screen is empty - even though I've confirmed with Wireshark that the UDP stream does reach the PC.

**Comment by jordens** [comment]
Is 10.255.6.129 the IP that the packets are being sent **to**?

**Comment by jordens** [comment]
And do they pass a/the firewall?

**Comment by jordens** [comment]
For windows maybe you need some other features [here](https://github.com/quartiq/stabilizer-stream/blob/3cfb3ad6a0b3ae51fb509c72a8ef982f6631fb30/Cargo.toml#L18C1-L19C1) Play with the egui/eframe examples and see whether you can get them to run. OTOH as @ryan-summers indicates, it does run for him fine on Windows: it may be something particular to your system or his.

**Comment by juhaszp95** [comment]
Yes, this is the IP of the computer the program is being run on. Wireshark is running on the same computer and can see the packets coming in.

**Comment by jordens** [comment]
Wireshark tends to capture before the firewall.

**Comment by jordens** [comment]
> the UI shows no FFT data coming in, the screen is empty

Just checked again with current repos and it works fine here.

Screenshot?

**Comment by ryan-summers** [comment]
> For windows maybe you need some other features [here](https://github.com/quartiq/stabilizer-stream/blob/3cfb3ad6a0b3ae51fb509c72a8ef982f6631fb30/Cargo.toml#L18C1-L19C1) Play with the egui/eframe examples and see whether you can get them to run. OTOH as @ryan-summers indicates, it does run for him fine on Windows: it may be something particular to your system or his.

I run almost everything in Git Bash on Windows. Interestingly, when I try to run via powershell, it also doesn't do anything for me. This seems like an egui issue or something with feature selection.

**Comment by juhaszp95** [comment]
Ha, the git bash works for me as well - thanks.

I'm now running this on Windows, where I have another application which definitely receives data from the very same stabilizer. (It's a UI to show the input/output from/to the stabilizer.)

Re the screenshot:
![image](https://github.com/quartiq/stabilizer-stream/assets/36235630/a21c7817-ea93-419e-81d5-a1ace4def85c)

**Comment by jordens** [comment]
Disable the `D` trace (click it) as that's zero and makes the auto-scaling fail.
Or just zoom out and scale manually (mouse wheel). egui/eframe has docs on how to interact with widgets somewhere.

**Comment by juhaszp95** [comment]
Ah, it's all there now, thanks very much!
